---
title: "Writing Functions"
author: "Yuying Lu"
date: "2024-10-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rvest)
```

## writing my first function!

as an example, here's a z-score computation

```{r}
x_vec = rnorm(n=25, mean = 10, sd = 3.5)
(x_vec - mean(x_vec)) / sd(x_vec)
```
Now I'll write a function to do this:

```{r}
z_scores = function(x){
  if (!is.numeric(x)){
    stop("x needs to be numeric")
  }
  if (length(x) < 5){
    stop("you need at least five numbers to compute the z score")
  }
  z = (x - mean(x)) / sd(x)
  return(z)
}

z_scores(x_vec)
```

does this always work?

```{r, error = TRUE}
z_scores(x = 3)
z_scores(c('my', 'name', 'is', 'Yuying'))
```

## A new function!


```{r}
mean_and_sd = function(x){
  mean_x = mean(x)
  sd_x = sd(x)
  out_df = tibble(
    mean = mean_x,
    sd = sd_x
  )
  return(out_df)
}

mean_and_sd(x_vec)
```

## Check stuff using a simulation

```{r}
sim_df = 
  tibble(
    x = rnorm(30, 10, 5)
  )

sim_df |> 
  summarise(
    mean = mean(x),
    sd = sd(x)
  )
```

## Simulation function to check sample mean and sd.

```{r}
sim_mean_sd = function(sample_size, true_mean = 10, true_sd = 5){
  
  sim_df = 
    tibble(
      x = rnorm(sample_size, true_mean, true_sd)
    )
  out_df = 
    sim_df |> 
    summarise(
      mean = mean(x),
      sd = sd(x)
    )
  return(out_df)
}

sim_mean_sd(sample_size = 3000, true_mean = 4, true_sd = 12)
sim_mean_sd(true_mean = 4, true_sd = 12, sample_size = 3000)
sim_mean_sd(3000, 4, 12)
sim_mean_sd(3000,,4)
sim_mean_sd(3000,4)

```


```{r}

fellowship_df = readxl::read_excel("LotR_Words.xlsx", range = "B3:D6") |>
  mutate(movie = "fellowship_ring")

two_towers_df = readxl::read_excel("LotR_Words.xlsx", range = "F3:H6") |>
  mutate(movie = "two_towers")

return_king_df = readxl::read_excel("LotR_Words.xlsx", range = "J3:L6") |>
  mutate(movie = "return_king")

lotr_tidy = bind_rows(fellowship_ring, two_towers, return_king) |>
  janitor::clean_names() |>
  pivot_longer(
    female:male,
    names_to = "sex",
    values_to = "words") |> 
  mutate(race = str_to_lower(race)) |> 
  select(movie, everything()) 
```


```{r}
read_df = function(file_name, range, movie_name){
  df = 
    readxl::read_excel(file_name, range = range) |>
  mutate(movie = movie_name) |> 
    janitor::clean_names() |> 
    pivot_longer(
      female:male,
      names_to = "sex",
      values_to = "words") |>
    mutate(
      race = str_to_lower(race),
      movie = movie_name) |> 
    select(movie, everything())
  
  return(df)
}

read_df('LotR_Words.xlsx', 'B3:D6', 'fellowship_ring')
```

## NSDUH

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)

data_marj = 
  nsduh_html |> 
  html_table() |> 
  nth(1) |>
  slice(-1) |> 
  select(-contains("P Value")) |>
  pivot_longer(
    -State,
    names_to = "age_year", 
    values_to = "percent") |>
  separate(age_year, into = c("age", "year"), sep = "\\(") |>
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_replace(percent, "[a-c]$", ""),
    percent = as.numeric(percent)) |>
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
data_marj
```

```{r}
nsduh_table_format = function(table_order, drug_name){
  out_table = 
    nsduh_html |> 
    html_table() |> 
    nth(table_order) |>
    slice(-1) |> 
    mutate(drug = drug_name)
  return(out_table)
}

html_table(,1,'marj')
html_table(4,'cocaine')
html_table(5,'herion')
```

